# Generated by Django 4.1.1 on 2022-09-30 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Piggy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_income", models.FloatField(blank=True, null=True)),
                ("desired_item", models.CharField(blank=True, max_length=200)),
                ("desired_item_cost", models.FloatField(blank=True, null=True)),
                ("daily_expenses", models.FloatField(blank=True, null=True)),
                ("monthly_donations", models.FloatField(blank=True, null=True)),
                ("monthly_bills", models.FloatField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "saver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
